import { Child } from "./child-types";

export const mockChildren: Child[] = [
  {
    id: "mateo",
    name: "Mateo Fernández",
    initial: "M",
    avatarBg: "#A9D9E8",
    avatarColor: "#1F7A93",
    ageYears: 3,
    birthdateLabel: "12 mar 2022",
    room: "Soles",
    admissionLabel: "feb 2025",
    allergens: ["MANÍ"],
    allergyNotes: "Alergia al maní. Evitar frutos secos. Lleva inhalador en la mochila.",
    linkedParents: [
      {
        id: "lucia",
        name: "Lucía Fernández",
        email: "lucia.fernandez@example.com",
        initial: "L",
        avatarBg: "#C9B6E8",
        avatarColor: "#fff",
        role: "mom",
        roleLabel: "Mamá",
        status: "active",
        statusLabel: "ACTIVA",
      },
      {
        id: "diego",
        name: "Diego Fernández",
        email: "diego.fernandez@example.com",
        initial: "D",
        avatarBg: "#A9C7E8",
        avatarColor: "#fff",
        role: "dad",
        roleLabel: "Papá",
        status: "pending",
        statusLabel: "PENDIENTE",
      },
    ],
  },
  {
    id: "sofia",
    name: "Sofía Méndez",
    initial: "S",
    avatarBg: "#F4B8CC",
    avatarColor: "#C44A7A",
    ageYears: 2,
    birthdateLabel: "5 jun 2023",
    room: "Soles",
    admissionLabel: "mar 2025",
    allergens: [],
    linkedParents: [
      {
        id: "carla",
        name: "Carla Méndez",
        email: "carla.mendez@example.com",
        initial: "C",
        avatarBg: "#F4DC8E",
        avatarColor: "#9A7B1E",
        role: "mom",
        roleLabel: "Mamá",
        status: "active",
        statusLabel: "ACTIVA",
      },
    ],
  },
  {
    id: "benjamin",
    name: "Benjamín Ruiz",
    initial: "B",
    avatarBg: "#B9DEC4",
    avatarColor: "#3E8B62",
    ageYears: 3,
    birthdateLabel: "22 ene 2022",
    room: "Soles",
    admissionLabel: "feb 2025",
    allergens: [],
    linkedParents: [
      {
        id: "ana",
        name: "Ana Ruiz",
        email: "ana.ruiz@example.com",
        initial: "A",
        avatarBg: "#F4B8CC",
        avatarColor: "#C44A7A",
        role: "mom",
        roleLabel: "Mamá",
        status: "active",
        statusLabel: "ACTIVA",
      },
      {
        id: "pedro",
        name: "Pedro Ruiz",
        email: "pedro.ruiz@example.com",
        initial: "P",
        avatarBg: "#A9D9E8",
        avatarColor: "#1F7A93",
        role: "dad",
        roleLabel: "Papá",
        status: "active",
        statusLabel: "ACTIVA",
      },
    ],
  },
  {
    id: "valentina",
    name: "Valentina Soto",
    initial: "V",
    avatarBg: "#F4DC8E",
    avatarColor: "#9A7B1E",
    ageYears: 2,
    birthdateLabel: "14 sep 2023",
    room: "Soles",
    admissionLabel: "abr 2025",
    allergens: [],
    linkedParents: [],
  },
  {
    id: "tomas",
    name: "Tomás Díaz",
    initial: "T",
    avatarBg: "#C9B6E8",
    avatarColor: "#7B5FC0",
    ageYears: 3,
    birthdateLabel: "30 nov 2022",
    room: "Soles",
    admissionLabel: "feb 2025",
    allergens: ["LACTOSA"],
    linkedParents: [
      {
        id: "mariana",
        name: "Mariana Díaz",
        email: "mariana.diaz@example.com",
        initial: "M",
        avatarBg: "#B9DEC4",
        avatarColor: "#3E8B62",
        role: "mom",
        roleLabel: "Mamá",
        status: "active",
        statusLabel: "ACTIVA",
      },
    ],
  },
  {
    id: "emma",
    name: "Emma Castro",
    initial: "E",
    avatarBg: "#F4B8CC",
    avatarColor: "#C44A7A",
    ageYears: 2,
    birthdateLabel: "8 ago 2023",
    room: "Soles",
    admissionLabel: "mar 2025",
    allergens: [],
    linkedParents: [
      {
        id: "laura",
        name: "Laura Castro",
        email: "laura.castro@example.com",
        initial: "L",
        avatarBg: "#C9B6E8",
        avatarColor: "#7B5FC0",
        role: "mom",
        roleLabel: "Mamá",
        status: "active",
        statusLabel: "ACTIVA",
      },
    ],
  },
  {
    id: "lucas",
    name: "Lucas Romero",
    initial: "L",
    avatarBg: "#A9D9E8",
    avatarColor: "#1F7A93",
    ageYears: 3,
    birthdateLabel: "17 abr 2022",
    room: "Soles",
    admissionLabel: "feb 2025",
    allergens: [],
    linkedParents: [
      {
        id: "silvia",
        name: "Silvia Romero",
        email: "silvia.romero@example.com",
        initial: "S",
        avatarBg: "#F4DC8E",
        avatarColor: "#9A7B1E",
        role: "mom",
        roleLabel: "Mamá",
        status: "active",
        statusLabel: "ACTIVA",
      },
    ],
  },
  {
    id: "olivia",
    name: "Olivia Vega",
    initial: "O",
    avatarBg: "#B9DEC4",
    avatarColor: "#3E8B62",
    ageYears: 2,
    birthdateLabel: "25 dic 2023",
    room: "Soles",
    admissionLabel: "mar 2025",
    allergens: [],
    linkedParents: [
      {
        id: "martin",
        name: "Martín Vega",
        email: "martin.vega@example.com",
        initial: "M",
        avatarBg: "#A9C7E8",
        avatarColor: "#fff",
        role: "dad",
        roleLabel: "Papá",
        status: "active",
        statusLabel: "ACTIVA",
      },
    ],
  },
];

export function getChildById(id: string): Child | undefined {
  return mockChildren.find((child) => child.id === id);
}
